discord/urls.py
from django.conf.urls import url

from . import views

app_name = 'discord'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<guild>[0-9]+)/$', views.guild, name='guild'),
	url(r'^(?P<guild>[0-9]+)/(?P<channel>[0-9]+)/(?P<page>[0-9]+)/$', views.channel, name='channel'),
	url(r'^create/$', views.create, name='create'),
	url(r'^update/$', views.update, name='update'),
	url(r'^(?P<guild>[0-9]+)/(?P<channel>[0-9]+)/(?P<page>[0-9]+)/jump/$', views.jump, name='jump'),
	url(r'^(?P<channel>[0-9]+)/latest/$', views.latest, name='latest'),
	url(r'^search/(?P<page>[0-9]+)/$', views.search, name='search'),
	url(r'^search/$', views.searchhome, name='searchhome'),
	url(r'^user/(?P<user>[0-9]+)/(?P<page>[0-9]+)/$', views.searchuser, name='searchuser'),
	url(r'^(?P<guild>[0-9]+)/(?P<channel>[0-9]+)/find/(?P<message>[0-9]+)/$', views.find, name='find'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^discord/', include('discord.urls')),
]

discord/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Game(models.Model):
	name = models.TextField()

class User(models.Model):
	username = models.CharField(max_length=64)
	avatar = models.CharField(max_length=64, null=True, blank=True)
	id = models.CharField(max_length=64, primary_key=True)

class Guild(models.Model):
	id = models.CharField(max_length=64, primary_key=True)
	name = models.CharField(max_length=100)
	icon = models.CharField(max_length=64, null=True, blank=True)
	game = models.ForeignKey(Game, on_delete=models.SET_NULL, blank=True, null=True)

class Channel(models.Model):
	id = models.CharField(max_length=64, primary_key=True)
	guild = models.ForeignKey(Guild, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)

class Message(models.Model):
	id = models.CharField(max_length=64,primary_key=True)
	channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
	post_date = models.DateTimeField('Date Posted')
	last_edit = models.DateTimeField('Last Edit Date', null=True, blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	content = models.TextField()

class Attachment(models.Model):
	id = models.CharField(max_length=64,primary_key=True)
	message = models.ForeignKey(Message, on_delete=models.CASCADE)
	is_image = models.BooleanField(default=False)
	url = models.URLField()
	height = models.IntegerField(default=0)
	width = models.IntegerField(default=0)
	proxy_url = models.URLField()
	name = models.CharField(max_length=255)

discord/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from django.db.models import Q
from re import split as re_split
import datetime
import urllib

from .models import Guild, Channel, User, Message, Game, Attachment

def parse_time(timestamp):
	if timestamp:
		return datetime.datetime(*map(int, re_split(r'[^\d]', timestamp.replace('+00:00', ''))))
	return None

# Create your views here.
def index(request):
	games = Game.objects.order_by('name')
	misc = Guild.objects.filter(game__isnull=True)
	context = {'game_list': games, 'misc': misc}
	return render(request, 'discord/index.html', context)

def guild(request, guild):
	g = Guild.objects.get(id=guild)
	context = {'channels': g.channel_set.order_by('name'), 'guild': Guild.objects.get(id=guild)}
	return render(request, 'discord/guild.html', context)

def channel(request, guild, channel, page):
	g = Guild.objects.get(id=guild)
	c = g.channel_set.get(id=channel)
	last = (((len(c.message_set.values())-1)/50)+1)
	blist = [i for i in range(1, int(page))][-5:]
	flist = [i for i in range(int(page)+1, last+1)][:5]
	messages = c.message_set.order_by('post_date')[50*(int(page)-1):50*(int(page))]
	for message in messages:
		if "<@" in message.content:
			for word in message.content.split(" "):
				if "<@" in word:
					userid = word[2:-1]
					users = User.objects.filter(id=userid) 
					if len(users) == 1:
						message.content = message.content.replace(word, "@" + users[0].username)
		if "<#" in message.content:
			for word in message.content.split(" "):
				if "<#" in word:
					channelid = word[2:-1]
					channels = Channel.objects.filter(id=channelid) 
					if len(channels) == 1:
						message.content = message.content.replace(word, "#" + channels[0].name)
		#message.content = message.content.replace("<", "&lt;").replace(">", "&gt;")
	context = {'messages': messages, 'guild':g, 'channel':c, 'page':page, 'last':str(last), 'prev':int(page)-1, 'next':int(page)+1, 'blist':blist, 'flist':flist}
	return render(request, 'discord/channel.html', context)

def jump(request, guild, channel, page):
	try:
		p = request.POST['page']
	except (KeyError):
		return HttpResponse(status=404)
	else:
		return HttpResponseRedirect(reverse('discord:channel', args=(guild, channel, p,)))

def searchuser(request, user, page):
	#Render page with search results
	results = Message.objects.filter(user__id=user).order_by('-post_date')
	
	last = (((len(results)-1)/50)+1)
	blist = [i for i in range(1, int(page))][-5:]
	flist = [i for i in range(int(page)+1, last+1)][:5]
	messages = results[50*(int(page)-1):50*(int(page))]
	for message in messages:
		if "<@" in message.content:
			for word in message.content.split(" "):
				if "<@" in word:
					userid = word[2:-1]
					users = User.objects.filter(id=userid) 
					if len(users) == 1:
						message.content = message.content.replace(word, "@" + users[0].username)
		if "<#" in message.content:
			for word in message.content.split(" "):
				if "<#" in word:
					channelid = word[2:-1]
					channels = Channel.objects.filter(id=channelid) 
					if len(channels) == 1:
						message.content = message.content.replace(word, "#" + channels[0].name)
	
	context = {'messages': messages, 'page':page, 'last':str(last), 'prev':int(page)-1, 'next':int(page)+1, 'blist':blist, 'flist':flist, 'searched': True, 'total': len(results), 'guilds': Guild.objects.all(), 'query': urllib.urlencode(request.GET), 'userid': user}
	return render(request, 'discord/user.html', context)

def search(request, page):
	if 'querytext' in request.GET:
		#Render page with search results
		querytext = request.GET['querytext'] if 'querytext' in request.GET else None
		channels = request.GET['channel'] if 'channel' in request.GET else None
		guilds = request.GET['guild'] if 'guild' in request.GET else None
		games = request.GET['game'] if 'game' in request.GET else None
		users = request.GET['user'] if 'user' in request.GET else None
		
		query = Q()
		if querytext:
			query = Q(content__contains="" + querytext + "")
		
		if channels:
			q = Q()
			for channel in channels.split("+"):
				q = q | Q(channel__id=channel)
			query = query & q
		if guilds:
			q = Q()
			for guild in guilds.split("+"):
				q = q | Q(channel__guild__id=guild)
			query = query & q
		if games:
			q = Q()
			for game in games.split("+"):
				q = q | Q(channel__guild__game__id=game)
			query = query & q
		if users:
			q = Q()
			for user in users.split("+"):
				q = q | Q(user__username=user)
			query = query & q
		results = Message.objects.filter(query).order_by('-post_date')
		
		last = (((len(results)-1)/50)+1)
		blist = [i for i in range(1, int(page))][-5:]
		flist = [i for i in range(int(page)+1, last+1)][:5]
		messages = results[50*(int(page)-1):50*(int(page))]
		for message in messages:
			if "<@" in message.content:
				for word in message.content.split(" "):
					if "<@" in word:
						userid = word[2:-1]
						users = User.objects.filter(id=userid) 
						if len(users) == 1:
							message.content = message.content.replace(word, "@" + users[0].username)
			if "<#" in message.content:
				for word in message.content.split(" "):
					if "<#" in word:
						channelid = word[2:-1]
						channels = Channel.objects.filter(id=channelid) 
						if len(channels) == 1:
							message.content = message.content.replace(word, "#" + channels[0].name)
			#AAAAAAAAA
			message.content = message.content.replace("<", "&lt;").replace(">", "&gt;")
			message.content = message.content.replace("" + querytext + "", "<b>" + querytext + "</b>")
		
		pages = []
		"""for result in results:
			channel = result.channel
			index = channel.message_set.filter(post_date__lt = result.post_date).count()
			page = index/50+1
			asdf = "<a href='http://localhost:8000/discord/"+str(channel.guild.id)+"/"+str(channel.id)+"/"+str(page)+"/#"+str(result.id)+"'>Link</a>"
			pages.append((result.id, result.content, asdf))"""
		#context = {"message": pages}
		#return render(request, 'discord/results.html', context)
		#return HttpResponse(str(pages))
		context = {'messages': messages, 'page':page, 'last':str(last), 'prev':int(page)-1, 'next':int(page)+1, 'blist':blist, 'flist':flist, 'searched': True, 'total': len(results), 'guilds': Guild.objects.all(), 'query': urllib.urlencode(request.GET)}
		return render(request, 'discord/search.html', context)
	else:
		#Render the page without any results
		#return render(request, 'discord/results.html', {})
		return render(request, 'discord/search.html', {'guilds': Guild.objects.all(), 'searched': False})

def searchhome(request):
	return render(request, 'discord/search.html', {'guilds': Guild.objects.all(), 'searched': False})

def find(request, guild, channel, message):
	m = get_object_or_404(Message, id=message)
	c = get_object_or_404(Channel, id=channel)
	index = c.message_set.filter(post_date__lt = m.post_date).count()
	page = index/50+1
	return HttpResponseRedirect(reverse('discord:channel', args=(guild, channel, page,)) + "#" + str(message))

def latest(request, channel):
	c = get_object_or_404(Channel, id=channel)
	message = c.message_set.order_by('-post_date')[0]
	return HttpResponse(str(message.id))

@csrf_exempt
def update(request):
	if 'type' in request.POST:
		type = request.POST['type']
		if type == 'guild':
			id = request.POST['id']
			name = request.POST['name']
			icon = request.POST['icon']
			guild = Guild.objects.filter(id=id)
			if len(guild) == 1:
				guild = guild[0]
				guild.name = name
				guild.icon = icon
				guild.save()
				return HttpResponse(status=201)
			return HttpResponse(status=409)
		elif type == 'channel':
			id = request.POST['id']
			name = request.POST['name']
			channel = Channel.objects.filter(id=id)
			if len(channel) == 1:
				channel = channel[0]
				channel.name = name
				channel.save()
				return HttpResponse(status=201)
			return HttpResponse(status=409)
		elif type == 'user':
			id = request.POST['id']
			username = request.POST['username']
			avatar = request.POST['avatar']
			user = User.objects.filter(id=id)
			if len(user) == 1:
				user = user[0]
				user.username = username
				user.avatar = avatar
				user.save()
				return HttpResponse(status=201)
			return HttpResponse(status=409)
		elif type == 'message':
			id = request.POST['id']
			content = request.POST['content']
			edited = parse_time(request.POST['edited'])
			message = Message.objects.filter(id=id)
			if len(message) == 1:
				message = message[0]
				message.content = content
				message.last_edit = edited
				message.save()
				return HttpResponse(status=201)
			return HttpResponse(status=409)
		elif type == 'messagedelete':
			id = request.POST['id']
			message = Message.objects.filter(id=id)
			if len(message) == 1:
				message = message[0]
				message.delete()
				return HttpResponse(status=201)
			return HttpResponse(status=409)

@csrf_exempt
def create(request):
	if 'type' in request.POST:
		type = request.POST['type']
		if type == 'guild':
			id = request.POST['id']
			name = request.POST['name']
			icon = request.POST['icon']
			if not Guild.objects.filter(id=id).exists():
				guild = Guild(id=id, name=name, icon=icon)
				guild.save()
				return HttpResponse(status=201)
			return HttpResponse(status=409)
		elif type == 'channel':
			id = request.POST['id']
			name = request.POST['name']
			g = request.POST['guild']
			if Channel.objects.filter(id=id).exists():
				return HttpResponse(status=409)
			if Guild.objects.filter(id=g).exists():
				guild = Guild.objects.get(id=g)
				guild.channel_set.create(id=id, name=name)
				return HttpResponse(status=201)
			return HttpResponse(status=424)
		elif type == 'user':
			id = request.POST['id']
			username = request.POST['username']
			avatar = request.POST['avatar']
			if not User.objects.filter(id=id).exists():
				user = User(id=id, username=username, avatar=avatar)
				user.save()

discord/templates/discord/index.html
{% load staticfiles %}
<html>
<head>
		<title>Discord Archives - Definitely Not Dustloop</title>
		<link rel="stylesheet" type="text/css" href="{% static 'discord/framework.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/responsive.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/core.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/core_responsive.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/forums.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/forums_responsive.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/custom.css' %}" media="all">
</head>
<body class="ipsApp ipsApp_front ipsJS_has ipsClearfix" data-controller="core.front.core.app"  data-message=""  data-pageapp="forums" data-pagelocation="front" data-pagemodule="forums" data-pagecontroller="index" itemscope itemtype="http://schema.org/WebSite">
	<div id="ipsLayout_header" class="ipsClearfix">
		<header>
			<div class="ipsLayout_container">
				<a href="{% url 'discord:index' %}" id="elLogo" accesskey="1"><span style="color: rgb(250, 250, 250); font-size: 24px;">Definitely Not </span><img src="http://www.dustloop.com/forums/uploads/monthly_2016_03/lightdustloop.png.671eea959c3a5f000e6bd7fa99568b0e.png" alt="Not Dustloop Forums"></a>
			</div>
		</header>
		<nav class="ipsLayout_container" data-controller="core.front.core.navBar" id="ips_uid_5365_2">
			<div class="ipsNavBar_primary  ipsClearfix" style="color: rgb(250, 250, 250); padding-bottom: 5px;">
				I Totally Didn't Just Steal Dustloop's CSS
				
				<span id="elSearch" class="ipsPos_right" data-controller="core.front.core.quickSearch" itemprop="potentialAction" itemscope="" itemtype="http://schema.org/SearchAction" data-default="forums_topic">
					<form accept-charset="utf-8" action="{% url 'discord:search' 1 %}" method="get">
						<meta itemprop="target" content="{% url 'discord:search' 1 %}">
						<input type="search" id="elSearchField" placeholder="Search..." name="querytext" itemprop="query-input" style="right: 30;">
						<button type="submit" style="right: 1; color: rgb(0,0,0);">⌕</button>
					</form>
				</span>
			</div>
		</nav>
	</div>
	<main role="main" id="ipsLayout_body" class="ipsLayout_container">
		<div id="ipsLayout_contentArea">
			<div id="elHeaderNavigation" class="ipsSubNavigation">
				<nav class="ipsBreadcrumb ipsBreadcrumb_top ipsFaded_withHover">
					<ul itemscope="" itemtype="http://schema.org/BreadcrumbList">
						<li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
							<a href="{% url 'discord:index' %}" itemprop="url">
								<span itemprop="name">Home</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
			<div id="ipsLayout_contentWrapper">
				<div id="ipsLayout_mainArea">
					<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
						<h1 class="ipsType_pageTitle">Servers</h1>
					</div>
					<section>
						<ol class="ipsList_reset cForumList" data-controller="core.global.core.table, forums.front.forum.forumList" data-baseurl="">
							{% if game_list %}
							{% for game in game_list %}
							<li class="cForumRow ipsBox ipsSpacer_bottom">
								<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">
									{{ game.name }}
								</h2>
								<ol class="ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset" data-role="forums">
									{% for guild in game.guild_set.all|dictsort:"name" %}
									<li class="ipsDataItem ipsDataItem_responsivePhoto  ipsClearfix">
										<div class="ipsDataItem_icon ipsDataItem_category">
											{% if guild.icon %}
											<img src="https://cdn.discordapp.com/icons/{{ guild.id }}/{{ guild.icon }}.jpg" height="50" width="50" class="ipsItemStatus ipsItemStatus_custom ipsItemStatus_read" style="border-radius: 25px">
											{% else %}
											<img src="https://discordapp.com/assets/6debd47ed13483642cf09e832ed0bc1b.png" height="50" width="50" class="ipsItemStatus ipsItemStatus_custom ipsItemStatus_read" style="border-radius: 25px">
											{% endif %}
										</div>
										<div class="ipsDataItem_main" style="display: table-cell;">
											<h4 class="ipsDataItem_title ipsType_large">
												<a href="{% url 'discord:guild' guild.id %}">{{ guild.name }}</a>
											</h4>
											<div class="ipsDataItem_meta ipsType_richText"><p></p></div>
										</div>
									</li>
									{% endfor %}
								</ol>
							</li>
							{% endfor %}
							{% endif %}
							{% if misc %}
							<li class="cForumRow ipsBox ipsSpacer_bottom">
								<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">
									Miscellaneous
								</h2>
								<ol class="ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset" data-role="forums">
									{% for guild in misc|dictsort:"name" %}
									<li class="ipsDataItem ipsDataItem_responsivePhoto  ipsClearfix">
										<div class="ipsDataItem_icon ipsDataItem_category">
											{% if guild.icon %}
											<img src="https://cdn.discordapp.com/icons/{{ guild.id }}/{{ guild.icon }}.jpg" height="50" width="50" class="ipsItemStatus ipsItemStatus_custom ipsItemStatus_read" style="border-radius: 25px">
											{% else %}
											<img src="https://discordapp.com/assets/6debd47ed13483642cf09e832ed0bc1b.png" height="50" width="50" class="ipsItemStatus ipsItemStatus_custom ipsItemStatus_read" style="border-radius: 25px">
											{% endif %}
										</div>
										<div class="ipsDataItem_main" style="display: table-cell;">
											<h4 class="ipsDataItem_title ipsType_large">
												<a href="{% url 'discord:guild' guild.id %}">{{ guild.name }}</a>
											</h4>
											<div class="ipsDataItem_meta ipsType_richText"><p></p></div>
										</div>
									</li>
									{% endfor %}
								</ol>
							</li>
							{% endif %}
						</ol>
					</section>
				</div>
			</div>
		</div>
	</main>
</body>
</html>

discord/templates/discord/user.html
{% load staticfiles %}
{% load mathfilters %}
<html lang="en-US" dir="ltr">
<head>
		<title>Search</title>
		<link rel="stylesheet" type="text/css" href="{% static 'discord/framework.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/responsive.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/core.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/core_responsive.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/forums.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/forums_responsive.css' %}" media="all">
		<link rel="stylesheet" type="text/css" href="{% static 'discord/custom.css' %}" media="all">
</head>
<body class="ipsApp ipsApp_front ipsJS_has ipsClearfix" data-controller="core.front.core.app"  data-message=""  data-pageapp="forums" data-pagelocation="front" data-pagemodule="forums" data-pagecontroller="index" itemscope itemtype="http://schema.org/WebSite">
	<div id="ipsLayout_header" class="ipsClearfix">
		<header>
			<div class="ipsLayout_container">
				<a href="{% url 'discord:index' %}" id="elLogo" accesskey="1"><span style="color: rgb(250, 250, 250); font-size: 24px;">Definitely Not </span><img src="http://www.dustloop.com/forums/uploads/monthly_2016_03/lightdustloop.png.671eea959c3a5f000e6bd7fa99568b0e.png" alt="Not Dustloop Forums"></a>
			</div>
		</header>
		
	</div>
	<main role="main" id="ipsLayout_body" class="ipsLayout_container">
		<div id="ipsLayout_contentArea">
			<div id="elHeaderNavigation" class="ipsSubNavigation" style="border-radius: 3px 3px 0px 0px;">
				<nav class="ipsLayout_container" data-controller="core.front.core.navBar" id="ips_uid_5365_2" style="padding: 0px; max-width: 100%">
					<div class="ipsNavBar_primary ipsClearfix" style="color: rgb(250, 250, 250); padding: 5px 5px 5px 5px;">
						I Totally Didn't Just Steal Dustloop's CSS
				
						<span id="elSearch" class="ipsPos_right" data-controller="core.front.core.quickSearch" itemprop="potentialAction" itemscope="" itemtype="http://schema.org/SearchAction" data-default="forums_topic">
							<form accept-charset="utf-8" action="{% url 'discord:search' 1 %}" method="get">
								<meta itemprop="target" content="{% url 'discord:search' 1 %}">
								<input type="search" id="elSearchField" placeholder="Search..." name="querytext" itemprop="query-input" style="right: 30;">
								<button type="submit" style="right: 1; color: rgb(0,0,0);">⌕</button>
							</form>
						</span>
					</div>
				</nav>
				<nav class="ipsBreadcrumb ipsBreadcrumb_top ipsFaded_withHover" style="display: block;">
					<ul itemscope="" itemtype="http://schema.org/BreadcrumbList">
						<li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem" style="display: table-cell;">
							<a href="{% url 'discord:index' %}" itemprop="url">
								<span itemprop="name">Home</span>
							</a>
						</li>
						<li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"style="display: table-cell;">
							<span itemprop="name">/</span>
							<a href="{% url 'discord:searchhome' %}" itemprop="url">
								<span itemprop="name">Search</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
			<div id="ipsLayout_contentWrapper">
				<!--div class="cWidgetContainer " data-role="widgetReceiver" data-orientation="horizontal" data-widgetarea="header">
					<ul class="ipsList_reset">
						
							
								<li class="ipsWidget ipsWidget_horizontal ipsBox ipsWidgetHide ipsHide" data-blockid="app_core_announcements_announcements" data-blockconfig="true" data-blocktitle="Announcements" data-controller="core.front.widgets.block"></li>
							
						
					</ul>
				</div-->
				<div id="ipsLayout_mainArea">
					<div data-controller="core.front.search.main" data-baseurl="http://www.dustloop.com/forums/index.php?/search/">
						<div class="ipsResponsive_hidePhone ipsResponsive_block ipsPageHeader">
							<h1 class="ipsType_pageTitle">Search the Community</h1>
							<p class="ipsType_reset ipsType_large ipsHide" data-role="searchBlurb"></p>
						</div>
						{% if searched %}
						<div id="elSearch_main" class="ipsSpacer_top" data-role="filterContent">
							<div data-controller="core.front.search.results" data-role="resultsArea">
								<p class="ipsType_sectionTitle ipsType_reset">Found {{ total }} results</p>
									<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
										<ul class="ipsPagination">
											{% if page != "1" %}
											<li class="ipsPagination_first"><a href="{% url 'discord:searchuser' userid 1 %}?{{ query }}"><<</a></li>
											<li class="ipsPagination_prev"><a href="{% url 'discord:searchuser' userid prev %}?{{ query }}">Prev</a></li>
											{% endif %}
											{% for i in blist %}
											<li class="ipsPagination_page"><a href="{% url 'discord:searchuser' userid i %}?{{ query }}">{{ i }}</a></li>
											{% endfor %}
											<li class="ipsPagination_page ipsPagination_active"><a href="{% url 'discord:searchuser' userid page %}?{{ query }}">{{ page }}</a></li>
											{% for i in flist %}
											<li class="ipsPagination_page"><a href="{% url 'discord:searchuser' userid i %}?{{ query }}">{{ i }}</a></li>
											{% endfor %}
											{% if page != last %}
											<li class="ipsPagination_next"><a href="{% url 'discord:searchuser' userid next %}?{{ query }}">Next</a></li>
											<li class="ipsPagination_last"><a href="{% url 'discord:searchuser' userid last %}?{{ query }}">>></a></li>
											{% endif %}
											<!--li class="ipsPagination_pageJump">
												<a href="#">Page {{ page }} of {{ last }} &nbsp;</a>
												<form accept-charset="utf-8" method="post" action="jump/">
													<ul class="ipsForm ipsForm_horizontal">
														<li class="ipsFieldRow">
															<input type="number" min="1" max="{{ last }}" placeholder="Page number" class="ipsField_fullWidth" name="page">
														</li>
														<li class="ipsFieldRow ipsFieldRow_fullWidth">
															<input type="submit" class="ipsButton_fullWidth ipsButton ipsButton_verySmall ipsButton_primary" value="Go">
														</li>
													</ul>
												</form>
											</li-->
										</ul>
									</div>
								<div class="ipsAreaBackground_light ipsPad">
									<ol class="ipsStream ipsList_reset" data-role="resultsContents">
										{% for message in messages %}
										<li data-controller="core.front.statuses.status" class="ipsStreamItem ipsStreamItem_contentBlock   ipsAreaBackground_reset ipsPad" data-timestamp="1358446027" data-role="activityItem" data-statusid="60093" data-processed="true">
											<div class="ipsStreamItem_container">
												<div class="ipsStreamItem_header ipsPhotoPanel ipsPhotoPanel_mini">
													{% if message.user.avatar %}
													<img class="ipsUserPhoto ipsUserPhoto_mini" src="https://cdn.discordapp.com/avatars/{{ message.user.id }}/{{ message.user.avatar }}.jpg" alt="{{ message.user.username }}" style="border-radius: 50%">
													{% else %}
													<img class="ipsUserPhoto ipsUserPhoto_mini" src="https://discordapp.com/assets/6debd47ed13483642cf09e832ed0bc1b.png" alt="{{ message.user.username }}" style="border-radius: 50%">
													{% endif %}
													<div>
														<h2 class="ipsType_reset ipsStreamItem_title  ipsType_break">
															<strong>
																{{ message.user.username }}
															</strong>
														</h2>
													</div>
												</div>
												<div class="ipsStreamItem_snippet">
													<div class="ipsType_richText ipsType_normal ipsContained">
														<p>{{ message.content }}</p>
														{% if message.attachment_set.all %}
															{% for attachment in message.attachment_set.all %}
																<p>
																{% if attachment.is_image %}
																	<a href="{{ attachment.url }}">
																		<img src="{{ attachment.proxy_url }}?height={{ attachment.height }}&width={{ attachment.width }}" alt="{{ attachment.name }}" title="{{ attachment.name }}">
																	</a>
																{% else %}
																	Attached: <a href="{{ attachment.url }}">{{ attachment.name }}</a>
																{% endif %}
																</p>
															{% endfor %}
														{% endif %}
													</div>
												</div>
												<ul class="ipsList_inline ipsStreamItem_meta ipsFaded_withHover">
													<li class="ipsType_medium">
														<a href="{% url 'discord:find' message.channel.guild.id message.channel.id message.id %}" class="ipsType_blendLinks">
															<span class="ipsType_light">
																◴
																Posted {{ message.post_date|date }} {{ message.post_date|time }}
																{% if message.last_edit %}
																 (edited)
																{% endif %}
															</span>
														</a>
												<a href="{% url 'discord:find' message.channel.guild.id message.channel.id message.id %}" class="ipsType_blendLinks" style="position: absolute; right: 30px; bottom: 5px;">To Post --></a>
													</li>
												</ul>
											</div>
										</li>
										{% endfor %}
									</ol>
								</div>
							</div>
						</div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</main>
</body>
</html>